name: Daily All Green Check

on:
  schedule:
    - cron: "0 12 * * *" # Runs daily at noon UTC
  workflow_dispatch: # Allow manual runs

jobs:
  check-green:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Install dependencies
        run: npm install

      - name: Run allGreen2025 script
        run: node green-lantern.js
        env:
          USERNAME: ${{ secrets.USERNAME }}
          TOKEN: ${{ secrets.AUTH_TOKEN }}
          TWILIO_ACCOUNT_SID: ${{ secrets.TWILIO_ACCOUNT_SID }}
          TWILIO_AUTH_TOKEN: ${{ secrets.TWILIO_AUTH_TOKEN }}
          TWILIO_WHATSAPP_TO: ${{ secrets.TWILIO_WHATSAPP_TO }}
